import json
import os
import shutil
import subprocess
import sys

from settings_projection import build_hooks

CATEGORIES = ["rules", "contexts", "hooks"]
LEGACY_CATEGORIES = ["agents"]
SKILLS_PRESERVE = {
    ".system",
    "vercel-composition-patterns",
    "vercel-react-best-practices",
    "web-design-guidelines",
}

repo_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
source_dir = os.path.join(repo_dir, "deploy")
base_settings_source = os.path.join(source_dir, "base-settings.json")
# 직접 복사하지 않고 settings 생성의 재료로만 쓰는 root 파일들.
# base-settings.json(공통 hook)과 타겟별 override(claude/gemini-settings.json).
SOURCE_ONLY_ROOT_FILES = {"base-settings.json", "claude-settings.json", "gemini-settings.json"}


# 각 타겟 설정 = base에서 만든 것(hook) + 타겟 override 파일. override가 우선(키 충돌 시 덮어씀).
def load_base_settings():
    if not (os.path.exists(base_settings_source) and os.path.isfile(base_settings_source)):
        raise RuntimeError(f"base-settings.json을 찾을 수 없습니다: {base_settings_source}")
    return read_json(base_settings_source)


# 타겟 override 파일(없으면 {}). base 재료를 덮어쓰는 타겟 전용 설정.
def load_override(name):
    override_path = os.path.join(source_dir, name)
    if os.path.exists(override_path) and os.path.isfile(override_path):
        return read_json(override_path)
    return {}


def claude_settings_object():
    result = {"hooks": build_hooks(load_base_settings()["hooks"], "claude")}
    result.update(load_override("claude-settings.json"))
    return result


def gemini_settings_object():
    # gemini는 hook 런타임이 없어 base hook을 받지 않는다. override 파일만(현재 없음 → {}).
    result = {}
    result.update(load_override("gemini-settings.json"))
    return result


def codex_hooks_object():
    return {"hooks": build_hooks(load_base_settings()["hooks"], "codex")}


def default_claude_dir():
    return os.path.join(os.path.expanduser("~"), ".claude")


def default_codex_dir():
    return os.path.join(os.path.expanduser("~"), ".codex")


def default_gemini_dir():
    return os.path.join(os.path.expanduser("~"), ".gemini")


def resolve_user_path(value):
    if not value or value == "~":
        return os.path.expanduser("~")
    if value.startswith("~" + os.sep) or value.startswith("~/") or value.startswith("~\\"):
        return os.path.join(os.path.expanduser("~"), value[2:])
    return os.path.abspath(value)


def ensure_deploy_source():
    if not (os.path.exists(source_dir) and os.path.isdir(source_dir)):
        raise RuntimeError(f"Deploy source not found: {source_dir}")


def ensure_dir(directory):
    os.makedirs(directory, exist_ok=True)


def remove_path(target):
    if os.path.islink(target) or os.path.isfile(target):
        try:
            os.remove(target)
        except FileNotFoundError:
            pass
    elif os.path.isdir(target):
        shutil.rmtree(target, ignore_errors=True)


def copy_path(src, dest):
    remove_path(dest)
    ensure_dir(os.path.dirname(dest))
    if os.path.isdir(src):
        shutil.copytree(src, dest)
    else:
        shutil.copy2(src, dest)


def read_json(file):
    with open(file, "r", encoding="utf-8") as handle:
        raw = handle.read().strip()
    return json.loads(raw) if raw else {}


def write_json(file, value):
    ensure_dir(os.path.dirname(file))
    with open(file, "w", encoding="utf-8") as handle:
        handle.write(json.dumps(value, indent=2, ensure_ascii=False) + "\n")


def build_agents_content(target_file_name):
    sections = [
        {"title": "Global Instructions", "file": os.path.join(source_dir, "CLAUDE.md")},
    ]

    rules_dir = os.path.join(source_dir, "rules")
    if os.path.exists(rules_dir) and os.path.isdir(rules_dir):
        files = sorted([f for f in os.listdir(rules_dir) if f.endswith(".md")])
        for file in files:
            if file == "global.md":
                title = "Global Rules"
            else:
                title = f"Global Rules - {os.path.splitext(file)[0].upper()}"
            sections.append({"title": title, "file": os.path.join(rules_dir, file)})

    parts = []
    for section in sections:
        if not (os.path.exists(section["file"]) and os.path.isfile(section["file"])):
            continue
        relative_path = os.path.relpath(section["file"], source_dir).replace("\\", "/")
        with open(section["file"], "r", encoding="utf-8") as handle:
            content = handle.read().strip()
        parts.append(
            f"# {section['title']}\n\n<!-- Source: deploy/{relative_path} -->\n\n{content}"
        )

    body = "\n\n---\n\n".join(parts)

    lower_name = os.path.splitext(os.path.basename(target_file_name))[0].lower()
    return (
        f"<!-- Generated by ai-workflow make sync-system. Do not edit "
        f"~/.{lower_name}/{target_file_name} directly. -->\n\n{body}\n"
    )


def build_codex_agents_content():
    return build_agents_content("AGENTS.md")


def build_gemini_agents_content():
    return build_agents_content("GEMINI.md")


# 머지된 settings.json 옆에 AC가 넣은 top-level 키 목록을 기록하는 사이드카.
# 다음 sync에서 "지난번엔 AC가 넣었지만 이번 소스엔 없는 키"(고아)를 식별해 제거하는 데 쓴다.
# merge_settings는 소스 키를 추가만 하므로, 이 매니페스트 없이는 소스에서 사라진 키가 영영 잔존한다.
def settings_manifest_path(target_path):
    return os.path.join(os.path.dirname(target_path), f".{os.path.basename(target_path)}.ac-keys")


def read_managed_keys(target_path):
    manifest_path = settings_manifest_path(target_path)
    if not os.path.exists(manifest_path):
        return []
    try:
        with open(manifest_path, "r", encoding="utf-8") as handle:
            parsed = json.loads(handle.read())
        return parsed if isinstance(parsed, list) else []
    except Exception:
        return []


def merge_settings(deploy, target_path):
    deploy_keys = list(deploy.keys())
    existing = read_json(target_path) if os.path.exists(target_path) else {}

    # 지난 sync에서 AC가 넣었지만 이번 소스엔 없는 top-level 키(고아)를 제거한다.
    for key in read_managed_keys(target_path):
        if key not in deploy_keys:
            existing.pop(key, None)

    merged = {**existing, **deploy}
    write_json(target_path, merged)
    with open(settings_manifest_path(target_path), "w", encoding="utf-8") as handle:
        handle.write(json.dumps(deploy_keys) + "\n")


def split_settings(deploy, target_path):
    if not os.path.exists(target_path):
        manifest_path = settings_manifest_path(target_path)
        if os.path.exists(manifest_path):
            remove_path(manifest_path)
        return False

    existing = read_json(target_path)
    # 현재 소스 키 + 지난 AC 관리 키(고아)를 모두 제거한다.
    keys_to_remove = set(deploy.keys()) | set(read_managed_keys(target_path))
    for key in keys_to_remove:
        existing.pop(key, None)

    manifest_path = settings_manifest_path(target_path)
    if os.path.exists(manifest_path):
        remove_path(manifest_path)

    if len(existing) == 0:
        remove_path(target_path)
    else:
        write_json(target_path, existing)
    return True


def verify_settings(deploy, target_path):
    if not os.path.exists(target_path):
        return False

    target = read_json(target_path)
    return all(stable_json(deploy[key]) == stable_json(target.get(key)) for key in deploy.keys())


# whole-file 타겟(codex hooks.json)용: 부분키 비교가 아니라 전체 일치를 본다.
def verify_json_exact(expected, target_path):
    if not os.path.exists(target_path):
        return False
    return stable_json(read_json(target_path)) == stable_json(expected)


def stable_json(value):
    return json.dumps(value, ensure_ascii=False)


def list_entries(directory):
    if not os.path.exists(directory):
        return []
    return sorted(os.scandir(directory), key=lambda e: e.name)


def compare_paths(left, right):
    if not os.path.exists(left) or not os.path.exists(right):
        return False

    left_is_dir = os.path.isdir(left)
    right_is_dir = os.path.isdir(right)
    if left_is_dir != right_is_dir:
        return False

    if left_is_dir:
        left_entries = list_entries(left)
        right_entries = list_entries(right)
        if len(left_entries) != len(right_entries):
            return False

        for i in range(len(left_entries)):
            if left_entries[i].name != right_entries[i].name:
                return False
            if not compare_paths(
                os.path.join(left, left_entries[i].name),
                os.path.join(right, right_entries[i].name),
            ):
                return False
        return True

    with open(left, "rb") as lf, open(right, "rb") as rf:
        return lf.read() == rf.read()


def deploy_root_files(target_dir, log):
    copied = 0
    for entry in list_entries(source_dir):
        if not entry.is_file():
            continue
        if entry.name in SOURCE_ONLY_ROOT_FILES:
            continue

        src = os.path.join(source_dir, entry.name)
        dest = os.path.join(target_dir, entry.name)
        copy_path(src, dest)
        log(f"  COPY  {entry.name}")
        copied += 1

    merge_settings(claude_settings_object(), os.path.join(target_dir, "settings.json"))
    log("  MERGE settings.json")
    copied += 1
    return copied


def deploy_skills(target_dir, log):
    src_skills = os.path.join(source_dir, "skills")
    if not (os.path.exists(src_skills) and os.path.isdir(src_skills)):
        return 0

    target_skills = os.path.join(target_dir, "skills")
    ensure_dir(target_skills)

    copied = 0
    for entry in list_entries(src_skills):
        src = os.path.join(src_skills, entry.name)
        copy_path(src, os.path.join(target_skills, entry.name))
        log(f"  COPY  skills/{entry.name}")
        copied += 1
    return copied


def uninstall_skills(target_dir, log):
    skills_dir = os.path.join(target_dir, "skills")
    removed = 0
    for entry in list_entries(skills_dir):
        if entry.name in SKILLS_PRESERVE:
            continue

        remove_path(os.path.join(skills_dir, entry.name))
        log(f"  DEL   skills/{entry.name}")
        removed += 1
    return removed


def deploy_codex_globals(target_dir, log=print):
    ensure_dir(target_dir)
    uninstall_codex_globals(target_dir, log)

    copied = 0
    src_contexts = os.path.join(source_dir, "contexts")
    if os.path.exists(src_contexts) and os.path.isdir(src_contexts):
        copy_path(src_contexts, os.path.join(target_dir, "contexts"))
        log("  COPY  contexts/")
        copied += 1

    src_hooks = os.path.join(source_dir, "hooks")
    if os.path.exists(src_hooks) and os.path.isdir(src_hooks):
        copy_path(src_hooks, os.path.join(target_dir, "hooks"))
        log("  COPY  hooks/")
        copied += 1

    write_json(os.path.join(target_dir, "hooks.json"), codex_hooks_object())
    log("  WRITE hooks.json")
    copied += 1

    with open(os.path.join(target_dir, "AGENTS.md"), "w", encoding="utf-8") as handle:
        handle.write(build_codex_agents_content())
    log("  WRITE AGENTS.md")
    copied += 1

    copied += deploy_skills(target_dir, log)
    return copied


def deploy_gemini_globals(target_dir, log=print):
    ensure_dir(target_dir)
    uninstall_gemini_globals(target_dir, log)

    copied = 0
    src_contexts = os.path.join(source_dir, "contexts")
    if os.path.exists(src_contexts) and os.path.isdir(src_contexts):
        copy_path(src_contexts, os.path.join(target_dir, "contexts"))
        log("  COPY  contexts/")
        copied += 1

    # gemini(Antigravity CLI)는 hook 러너가 없어 hook을 발동하지 못한다. hook 본문을
    # ~/.gemini/hooks/로 복사하지 않는다 (러너 없는 dead artifact 방지).

    with open(os.path.join(target_dir, "GEMINI.md"), "w", encoding="utf-8") as handle:
        handle.write(build_gemini_agents_content())
    log("  WRITE GEMINI.md")
    copied += 1

    copied += deploy_skills(target_dir, log)

    merge_settings(gemini_settings_object(), os.path.join(target_dir, "settings.json"))
    log("  MERGE settings.json")
    copied += 1

    return copied


def uninstall_gemini_globals(target_dir, log=print):
    removed = 0
    contexts_dir = os.path.join(target_dir, "contexts")
    if os.path.exists(contexts_dir) and os.path.isdir(contexts_dir):
        remove_path(contexts_dir)
        log("  DEL   contexts/")
        removed += 1
    hooks_dir = os.path.join(target_dir, "hooks")
    if os.path.exists(hooks_dir) and os.path.isdir(hooks_dir):
        remove_path(hooks_dir)
        log("  DEL   hooks/")
        removed += 1
    gemini_file = os.path.join(target_dir, "GEMINI.md")
    if os.path.exists(gemini_file) and os.path.isfile(gemini_file):
        remove_path(gemini_file)
        log("  DEL   GEMINI.md")
        removed += 1
    target = os.path.join(target_dir, "settings.json")
    if split_settings(gemini_settings_object(), target):
        log("  SPLIT settings.json")
        removed += 1

    removed += uninstall_skills(target_dir, log)
    return removed


def trust_codex_hooks(target_dir, log=print, cwd=None):
    if cwd is None:
        cwd = repo_dir
    hooks_config = os.path.join(target_dir, "hooks.json")
    if not (os.path.exists(hooks_config) and os.path.isfile(hooks_config)):
        return 0

    response = run_codex_app_server(
        [{"method": "hooks/list", "params": {"cwds": [cwd]}}]
    )
    list_result = None
    for message in response:
        result = (message or {}).get("result") if isinstance(message, dict) else None
        if isinstance(result, dict) and isinstance(result.get("data"), list):
            list_result = result
            break

    hooks = []
    if list_result and isinstance(list_result.get("data"), list):
        for entry in list_result["data"]:
            hooks.extend(entry.get("hooks") or [])

    deployed_hooks = [
        hook
        for hook in hooks
        if os.path.abspath(hook.get("sourcePath") or "") == os.path.abspath(hooks_config)
    ]

    state = {}
    for hook in deployed_hooks:
        if not hook.get("key") or not hook.get("currentHash") or hook.get("isManaged"):
            continue
        state[hook["key"]] = {
            "enabled": True,
            "trusted_hash": hook["currentHash"],
        }

    if len(state) == 0:
        return 0

    run_codex_app_server(
        [
            {
                "method": "config/batchWrite",
                "params": {
                    "edits": [
                        {
                            "keyPath": "hooks.state",
                            "value": state,
                            "mergeStrategy": "upsert",
                        }
                    ],
                    "reloadUserConfig": True,
                },
            }
        ]
    )

    log(f"  TRUST hooks.state ({len(state)})")
    return len(state)


def resolve_codex_cli():
    explicit = os.environ.get("CODEX_CLI")
    if explicit and is_runnable_codex_cli(explicit):
        return explicit

    names = (
        ["codex.exe", "codex.cmd", "codex.bat", "codex"]
        if sys.platform == "win32"
        else ["codex"]
    )
    path_hit = find_on_path(names)
    if path_hit:
        return path_hit

    if sys.platform == "win32":
        candidates = [
            os.path.join(
                os.path.expanduser("~"), "AppData", "Local", "OpenAI", "Codex", "bin", "codex.exe"
            ),
            os.path.join(os.environ.get("LOCALAPPDATA", ""), "OpenAI", "Codex", "bin", "codex.exe"),
            *find_local_app_codex_bins(),
            *find_windows_app_codex_bins(),
        ]
        for candidate in candidates:
            if is_runnable_codex_cli(candidate):
                return candidate
        return None

    return None


def find_on_path(names):
    path_value = os.environ.get("PATH", "")
    dirs = [d for d in path_value.split(os.pathsep) if d]
    for directory in dirs:
        for name in names:
            candidate = os.path.join(directory, name)
            if is_runnable_codex_cli(candidate):
                return candidate
    return None


def find_local_app_codex_bins():
    roots = [
        os.path.join(os.path.expanduser("~"), "AppData", "Local", "OpenAI", "Codex", "bin"),
        os.path.join(os.environ.get("LOCALAPPDATA", ""), "OpenAI", "Codex", "bin"),
    ]
    candidates = []

    seen = []
    for root in roots:
        if root in seen:
            continue
        seen.append(root)
        if not root or not os.path.exists(root) or not os.path.isdir(root):
            continue

        for entry in os.listdir(root):
            entry_path = os.path.join(root, entry)
            try:
                if os.path.isdir(entry_path):
                    candidates.append(os.path.join(entry_path, "codex.exe"))
            except Exception:
                # Ignore stale package directories while scanning Desktop-managed bins.
                pass

    def mtime(path):
        try:
            return os.stat(path).st_mtime
        except Exception:
            return 0

    candidates.sort(key=mtime, reverse=True)
    return candidates


def find_windows_app_codex_bins():
    windows_apps = os.path.join(
        os.environ.get("ProgramFiles") or "C:\\Program Files", "WindowsApps"
    )
    if not (os.path.exists(windows_apps) and os.path.isdir(windows_apps)):
        return []

    try:
        result = []
        for entry in os.listdir(windows_apps):
            if entry.startswith("OpenAI.Codex_"):
                result.append(
                    os.path.join(windows_apps, entry, "app", "resources", "codex.exe")
                )
                result.append(os.path.join(windows_apps, entry, "app", "resources", "codex"))
        return result
    except Exception:
        return []


def is_executable_file(file):
    if not file:
        return False
    try:
        return os.path.exists(file) and os.path.isfile(file)
    except Exception:
        return False


def is_runnable_codex_cli(file):
    if not is_executable_file(file):
        return False

    try:
        result = subprocess.run(
            [file, "--version"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            timeout=5,
        )
    except Exception:
        return False

    return result.returncode == 0


def run_codex_app_server(requests, options=None):
    options = options or {}
    cwd = options.get("cwd") or repo_dir
    timeout_seconds = (options.get("timeoutMs") or 30000) / 1000.0

    codex_cli = resolve_codex_cli()
    if not codex_cli:
        raise RuntimeError(
            "Codex CLI not found. Install Codex Desktop/CLI, add codex to PATH, "
            "or set CODEX_CLI to the codex executable path."
        )

    import threading

    child = subprocess.Popen(
        [codex_cli, "app-server", "--listen", "stdio://"],
        cwd=cwd,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        text=True,
        encoding="utf-8",
    )

    results = []
    pending = {}
    next_id = [1]
    stderr_buf = []
    settled = {"done": False, "error": None}
    lock = threading.Lock()
    finished = threading.Event()

    def finish(error):
        with lock:
            if settled["done"]:
                return
            settled["done"] = True
            settled["error"] = error
        try:
            child.kill()
        except Exception:
            pass
        finished.set()

    def send(method, params):
        request_id = next_id[0]
        next_id[0] += 1
        pending[request_id] = len(results)
        results.append(None)
        child.stdin.write(json.dumps({"id": request_id, "method": method, "params": params}) + "\n")
        child.stdin.flush()

    def read_stdout():
        try:
            for line in child.stdout:
                for raw in line.replace("\r\n", "\n").split("\n"):
                    if not raw.strip():
                        continue
                    try:
                        message = json.loads(raw)
                    except Exception:
                        continue

                    msg_id = message.get("id")
                    if not msg_id or msg_id not in pending:
                        continue
                    index = pending.pop(msg_id)
                    results[index] = message

                    if message.get("error"):
                        finish(
                            RuntimeError(
                                f"codex app-server {msg_id} failed: "
                                f"{json.dumps(message['error'])}"
                            )
                        )
                        return

                    if msg_id == 1:
                        child.stdin.write(
                            json.dumps({"method": "initialized", "params": {}}) + "\n"
                        )
                        child.stdin.flush()
                        for request in requests:
                            send(request["method"], request["params"])
                    elif len(pending) == 0:
                        finish(None)
                        return
        except Exception:
            pass

    def read_stderr():
        try:
            for line in child.stderr:
                stderr_buf.append(line)
        except Exception:
            pass

    stdout_thread = threading.Thread(target=read_stdout, daemon=True)
    stderr_thread = threading.Thread(target=read_stderr, daemon=True)
    stdout_thread.start()
    stderr_thread.start()

    send(
        "initialize",
        {
            "clientInfo": {"name": "ai-workflow-deploy", "version": "1.0.0"},
            "capabilities": {"experimentalApi": True},
        },
    )

    triggered_timeout = not finished.wait(timeout_seconds)
    if triggered_timeout:
        finish(RuntimeError("codex app-server timed out"))

    try:
        exit_code = child.wait(timeout=5)
    except Exception:
        exit_code = None
    if not settled["done"] and exit_code not in (0, None):
        finish(RuntimeError(f"codex app-server exited with {exit_code}"))

    error = settled["error"]
    if error:
        stderr_text = "".join(stderr_buf).strip()
        if stderr_text:
            error.args = (f"{error.args[0]}\n{stderr_text}",)
        raise error
    return results


def uninstall_codex_globals(target_dir, log=print):
    removed = 0
    contexts_dir = os.path.join(target_dir, "contexts")
    if os.path.exists(contexts_dir) and os.path.isdir(contexts_dir):
        remove_path(contexts_dir)
        log("  DEL   contexts/")
        removed += 1
    hooks_dir = os.path.join(target_dir, "hooks")
    if os.path.exists(hooks_dir) and os.path.isdir(hooks_dir):
        remove_path(hooks_dir)
        log("  DEL   hooks/")
        removed += 1
    hooks_config = os.path.join(target_dir, "hooks.json")
    if os.path.exists(hooks_config) and os.path.isfile(hooks_config):
        remove_path(hooks_config)
        log("  DEL   hooks.json")
        removed += 1
    agents_file = os.path.join(target_dir, "AGENTS.md")
    if os.path.exists(agents_file) and os.path.isfile(agents_file):
        remove_path(agents_file)
        log("  DEL   AGENTS.md")
        removed += 1
    removed += uninstall_skills(target_dir, log)
    return removed


def uninstall_target(target_dir, options=None):
    options = options or {}
    log = options.get("log", print)
    remove_alias = options.get("removeAlias", True)
    removed = 0

    for category in [*CATEGORIES, *LEGACY_CATEGORIES]:
        target = os.path.join(target_dir, category)
        if os.path.exists(target) and os.path.isdir(target):
            remove_path(target)
            log(f"  DEL   {category}/")
            removed += 1

    removed += uninstall_skills(target_dir, log)

    for entry in list_entries(source_dir):
        if not entry.is_file():
            continue
        if entry.name in SOURCE_ONLY_ROOT_FILES:
            continue

        target = os.path.join(target_dir, entry.name)
        if os.path.exists(target) and os.path.isfile(target):
            remove_path(target)
            log(f"  DEL   {entry.name}")
            removed += 1

    settings = (
        gemini_settings_object() if target_dir == default_gemini_dir() else claude_settings_object()
    )
    target = os.path.join(target_dir, "settings.json")
    if split_settings(settings, target):
        log("  SPLIT settings.json")
        removed += 1

    if remove_alias:
        unset_wt_add_alias(log)

    return removed


# 구버전에서 등록하던 글로벌 git wt-add alias를 제거한다. 워크트리 의존성 복구는
# 이제 PostToolUse self-heal hook(post-worktree-install / post-enterworktree-install)이
# 전담하므로 alias는 폐기한다. sync/unsync 모두에서 호출해 잔여 alias를 정리한다.
def unset_wt_add_alias(log=print):
    try:
        subprocess.run(
            ["git", "config", "--global", "--unset", "alias.wt-add"],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
        )
    except FileNotFoundError:
        # git이 없으면 (ENOENT) JS는 무시했다(error.code === 'ENOENT'). 그 외는 raise.
        pass
    log("  OK   git wt-add 제거 완료")
