#!/usr/bin/env python3

import json
import os
import re
import sys
from datetime import datetime, timezone
from zoneinfo import ZoneInfo

# --- Config ---
PROJECTS_DIR = os.path.join(os.path.expanduser("~"), ".claude", "projects")
TIMEZONE = "Asia/Seoul"
_TZ = ZoneInfo(TIMEZONE)

# --- Cleaning ---

# 메시지 통째 제거 판정용 접두사
DROP_PREFIXES = [
    "This session is being continued from a previous conversation",
    "Base directory for this skill:",
    "Caveat: The messages below were generated by the user while running local commands",
]


def clean_text(raw):
    t = raw

    # 1. 내용 통째 제거 (태그 + 내용)
    t = re.sub(r"<local-command-caveat>[\s\S]*?</local-command-caveat>", "", t)
    t = re.sub(r"<local-command-stdout>[\s\S]*?</local-command-stdout>", "", t)
    t = re.sub(r"<local-command-stderr>[\s\S]*?</local-command-stderr>", "", t)
    t = re.sub(r"<teammate-message[\s\S]*?</teammate-message>", "", t)
    t = re.sub(r"<task-notification>[\s\S]*?</task-notification>", "", t)
    t = re.sub(r"<system-reminder>[\s\S]*?</system-reminder>", "", t)
    t = re.sub(r"<!--[\s\S]*?-->", "", t)

    # 2. 태그만 제거, 내용 보존
    t = re.sub(r"</?command-name>", "", t)
    t = re.sub(r"</?command-message>", "", t)
    t = re.sub(r"</?command-args>", "", t)

    # 3. 후처리
    t = re.sub(r"\n{3,}", "\n\n", t).strip()

    return t


def process_message(raw):
    """클리닝 후 메시지를 통째 제거해야 하는지 판정.
    None을 반환하면 제거, 문자열을 반환하면 유지."""
    cleaned = clean_text(raw)
    for prefix in DROP_PREFIXES:
        if cleaned.startswith(prefix):
            return None
    return cleaned


# --- JSONL Parsing ---


def extract_user_text(obj):
    msg = obj.get("message")
    if isinstance(msg, str):
        return msg
    if msg and msg.get("content") is not None:
        content = msg["content"]
        if isinstance(content, str):
            return content
        if isinstance(content, list):
            t = next((c for c in content if c.get("type") == "text"), None)
            if t:
                return t.get("text")
    return ""


def _parse_iso(ts):
    # JS new Date(timestamp) 호환. 'Z'를 UTC offset으로 변환해 파싱한다.
    return datetime.fromisoformat(ts.replace("Z", "+00:00"))


def _fmt_time(d):
    # toLocaleTimeString("ko-KR", {hour/min/sec 2-digit, hour12:false, Asia/Seoul})
    local = d.astimezone(_TZ)
    return local.strftime("%H:%M:%S")


def parse_session(filepath):
    with open(filepath, "r", encoding="utf-8") as handle:
        lines = [line for line in handle.read().split("\n") if line]
    first_time = None
    last_time = None
    messages = []
    index = 0

    for line in lines:
        try:
            obj = json.loads(line)
        except Exception:
            continue

        if obj.get("timestamp"):
            if not first_time:
                first_time = obj["timestamp"]
            last_time = obj["timestamp"]

        if obj.get("type") == "user":
            index += 1
            raw = extract_user_text(obj)
            cleaned = process_message(raw)
            if cleaned is None:
                continue  # 메시지 통째 제거

            if obj.get("timestamp"):
                ts = _fmt_time(_parse_iso(obj["timestamp"]))
            else:
                ts = ""

            messages.append({"index": index, "time": ts, "text": cleaned})

    if not first_time:
        return None

    start = _parse_iso(first_time)
    end = _parse_iso(last_time)
    duration_min = round((end.timestamp() - start.timestamp()) / 60)

    start_local = start.astimezone(_TZ)
    # toLocaleDateString("ko-KR", {year/month/day 2-digit}) → "2026. 06. 19."
    # → replace(/\. /g, "-") → "2026-06-19." → replace(/\./g, "") → "2026-06-19"
    date_str = start_local.strftime("%Y. %m. %d.").replace(". ", "-").replace(".", "")

    return {
        "start_time": _fmt_time(start),
        "end_time": _fmt_time(end),
        "date": date_str,
        "duration_min": duration_min,
        "message_count": len(messages),
        "messages": messages,
    }


# --- Project Key ---


def to_project_key(dirname):
    # C--Users-yizihn-WebstormProjects-main → WebstormProjects/main
    # C--Users-yizihn-workspace-quriously-quriously-admin → workspace/quriously/quriously-admin
    # 사용자명에 하이픈이 포함될 수 있으므로 알려진 루트 경로 기준으로 자른다
    roots = ["WebstormProjects", "workspace"]
    # .claude 특수 처리: C--Users-yizihn--claude-xxx → .claude/xxx
    if "--claude" in dirname:
        idx = dirname.index("--claude")
        return "." + dirname[idx + 1:].replace("-", "/")
    for root in roots:
        idx = dirname.find(root)
        if idx != -1:
            return dirname[idx:].replace("-", "/")
    # fallback: C--Users-XXX- 패턴 제거
    key = re.sub(r"^C--Users-.*?-(WebstormProjects|workspace)", r"\1", dirname).replace("-", "/")
    return key or dirname


# --- Commands ---


def _list_dirs():
    result = []
    for d in os.listdir(PROJECTS_DIR):
        try:
            if os.path.isdir(os.path.join(PROJECTS_DIR, d)):
                result.append(d)
        except Exception:
            pass
    return result


def cmd_projects():
    dirs = _list_dirs()

    results = []
    for d in dirs:
        full = os.path.join(PROJECTS_DIR, d)
        jsonls = [f for f in os.listdir(full) if f.endswith(".jsonl")]
        if len(jsonls) == 0:
            continue

        latest = sorted(
            (os.stat(os.path.join(full, f)).st_mtime for f in jsonls), reverse=True
        )[0]

        results.append(
            {
                "key": to_project_key(d),
                "path": d,
                "sessions": len(jsonls),
                "last_active": datetime.fromtimestamp(latest, tz=timezone.utc)
                .isoformat()
                .replace("+00:00", "Z")[0:10],
            }
        )

    results.sort(key=lambda r: r["sessions"], reverse=True)
    print(json.dumps(results, indent=2, ensure_ascii=False))


def find_project_dir(query):
    dirs = _list_dirs()

    # 1. key 끝부분 완전 일치 우선
    exact = None
    for d in dirs:
        key = to_project_key(d)
        segments = key.split("/")
        if segments[-1] == query or key.endswith("/" + query) or key == query:
            exact = d
            break
    if exact:
        return exact

    # 2. 부분 일치
    matches = [d for d in dirs if query in to_project_key(d)]

    if len(matches) == 0:
        sys.stderr.write(f'No project matching "{query}"\n')
        sys.exit(1)
    if len(matches) > 1:
        sys.stderr.write(f'Multiple projects match "{query}":\n')
        for m in matches:
            sys.stderr.write(f"  - {to_project_key(m)}\n")
        sys.exit(1)
    return matches[0]


def cmd_sessions(query):
    directory = find_project_dir(query)
    full = os.path.join(PROJECTS_DIR, directory)
    jsonls = [f for f in os.listdir(full) if f.endswith(".jsonl")]

    results = []
    for f in jsonls:
        filepath = os.path.join(full, f)
        parsed = parse_session(filepath)
        if not parsed:
            continue

        first_msg = ""
        first = next((m for m in parsed["messages"] if len(m["text"]) > 0), None)
        if first:
            first_msg = first["text"][0:80]

        results.append(
            {
                "session_id": f.replace(".jsonl", "")[0:8],
                "date": parsed["date"],
                "start": parsed["start_time"],
                "end": parsed["end_time"],
                "duration_min": parsed["duration_min"],
                "message_count": parsed["message_count"],
                "first_message": first_msg,
            }
        )

    results.sort(key=lambda r: (r["date"], r["start"]))
    print(json.dumps(results, indent=2, ensure_ascii=False))


def cmd_detail(session_id):
    # 모든 프로젝트에서 session ID로 검색
    dirs = _list_dirs()

    for d in dirs:
        full = os.path.join(PROJECTS_DIR, d)
        jsonls = [f for f in os.listdir(full) if f.endswith(".jsonl")]
        match = next((f for f in jsonls if f.startswith(session_id)), None)
        if match:
            parsed = parse_session(os.path.join(full, match))
            if not parsed:
                sys.stderr.write("Session has no data\n")
                sys.exit(1)

            result = {
                "session_id": match.replace(".jsonl", "")[0:8],
                "project": to_project_key(d),
                "date": parsed["date"],
                "start": parsed["start_time"],
                "end": parsed["end_time"],
                "duration_min": parsed["duration_min"],
                "message_count": parsed["message_count"],
                "messages": parsed["messages"],
            }

            print(json.dumps(result, indent=2, ensure_ascii=False))
            return

    sys.stderr.write(f'Session "{session_id}" not found\n')
    sys.exit(1)


# --- Main ---


def main():
    args = sys.argv[1:]
    command = args[0] if len(args) > 0 else None
    rest = args[1:]

    if command == "projects":
        cmd_projects()
    elif command == "sessions":
        if not rest:
            sys.stderr.write("Usage: kpi.py sessions <project>\n")
            sys.exit(1)
        cmd_sessions(rest[0])
    elif command == "detail":
        if not rest:
            sys.stderr.write("Usage: kpi.py detail <session-id>\n")
            sys.exit(1)
        cmd_detail(rest[0])
    else:
        sys.stderr.write("Usage: kpi.py <projects|sessions|detail> [args]\n")
        sys.exit(1)


if __name__ == "__main__":
    main()
